version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: mdp_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: mdp
      POSTGRES_USER: felipe
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: